### ISSUE TITLE
Failed due to net-ssh 4.1.0 or chef-13.1.29

### ISSUE THREAD

**Issue by sawanoboly** [higanworks/knife-zero#110]
```
ERROR: Errno::ECONNREFUSEDConnection refused - connect(2) for "127.0.0.1" port 1
ERROR: /usr/local/bundle/gems/net-ssh-4.1.0/lib/net/ssh/service/forward.rb:346:in `initialize'
/usr/local/bundle/gems/net-ssh-4.1.0/lib/net/ssh/service/forward.rb:346:in `new'
/usr/local/bundle/gems/net-ssh-4.1.0/lib/net/ssh/service/forward.rb:346:in `forwarded_tcpip'
/usr/local/bundle/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:615:in `channel_open'
/usr/local/bundle/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:540:in `dispatch_incoming_packets'
/usr/local/bundle/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:237:in `ev_preprocess'
/usr/local/bundle/gems/net-ssh-4.1.0/lib/net/ssh/connection/session.rb:229:in `preprocess'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:205:in `preprocess'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:449:in `block in preprocess'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:47:in `block in each'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:45:in `each'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:45:in `each'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:449:in `preprocess'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:430:in `process'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `block in loop'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `loop'
/usr/local/bundle/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `loop'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/knife/ssh.rb:353:in `ssh_command'
/usr/local/bundle/gems/knife-zero-1.18.0/lib/knife-zero/bootstrap_ssh.rb:34:in `ssh_command'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/knife/ssh.rb:592:in `run'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/knife/bootstrap.rb:406:in `run'
/usr/local/bundle/gems/knife-zero-1.18.0/lib/chef/knife/zero_bootstrap.rb:87:in `run'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/knife.rb:442:in `block in run_with_pretty_exceptions'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/knife.rb:441:in `run_with_pretty_exceptions'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/knife.rb:219:in `run'
/usr/local/bundle/gems/chef-13.1.29/lib/chef/application/knife.rb:156:in `run'
/usr/local/bundle/gems/chef-13.1.29/bin/knife:25:in `<top (required)>'
/usr/local/bundle/bin/knife:22:in `load'
/usr/local/bundle/bin/knife:22:in `<main>'
ERROR: RuntimeError: Helper exec finished with non-zero exit code
```

`port 1` ?

**Comment by sawanoboly** [comment]
between  29bea24..921706ef062a31714c395dd387a252bdfe46526f

**Comment by EugenMayer** [comment]
same issue here, cannot bootstrap a new client:

```
Connecting to 144.76.73.211
ERROR: ArgumentErrorwrong number of arguments (given 1, expected 2)
ERROR: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/net-ssh-4.1.0/lib/net/ssh.rb:263:in `configuration_for'
```
any quickfix?

**Comment by EugenMayer** [comment]
i guess https://github.com/higanworks/knife-zero/commit/e039778e33babbb6657b0a6efc99fee8ea2c5852 that one fixed it?

**Comment by EugenMayer** [comment]
For anybody else, fix already released, upgrade knife-zero:

```
chef exec gem update knife-zero
```

Thanks for the quickfix @sawanoboly
