### ISSUE TITLE
knife zero converge "name:xxx-*" ERROR: Too many open files

### ISSUE THREAD

**Issue by hendych** [higanworks/knife-zero#163]
# Background
Hi, I tried to run `knife zero converge` using query to converge my recipes on all of my nodes. I have ~30 nodes. 

# What do I do?
After I ran it using `knife zero converge "name:mynode-*", The terminal produce this error.

```
ERROR: Errno::EMFILEToo many open files - socket(2) for "127.0.0.1" port 8889
ERROR: /Users/xxx/.gem/gems/net-ssh-6.1.0/lib/net/ssh/service/forward.rb:397:in `initialize'
     /Users/xxx/.gem/gems/net-ssh-6.1.0/lib/net/ssh/service/forward.rb:397:in `new'
     /Users/xxx/.gem/gems/net-ssh-6.1.0/lib/net/ssh/service/forward.rb:397:in `forwarded_tcpip'
     /Users/xxx/.gem/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:623:in `channel_open'
     /Users/xxx/.gem/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:548:in `dispatch_incoming_packets'
     /Users/xxx/.gem/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:248:in `ev_preprocess'
     /Users/xxx/.gem/gems/net-ssh-6.1.0/lib/net/ssh/connection/session.rb:240:in `preprocess'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server.rb:205:in `preprocess'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:449:in `block in preprocess'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:47:in `block in each'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:45:in `each'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb:45:in `each'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:449:in `preprocess'
     /Users/xxx/.gem/gems/knife-zero-2.4.1/lib/knife-zero/net_ssh_multi_patch.rb:109:in `process'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `block in loop'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `loop'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:417:in `loop'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/session.rb:404:in `close'
     /Users/xxx/.gem/gems/knife-17.7.29/lib/chef/knife/ssh.rb:412:in `ensure in ssh_command'
     /Users/xxx/.gem/gems/knife-17.7.29/lib/chef/knife/ssh.rb:412:in `ssh_command'
```

# What is the expected behavior?
The `knife zero converge QUERY` should be able to converge and open ssh without any problem

**Comment by sawanoboly** [comment]
To identify the problem, I need some information.

- Workstation environment
- Number of nodes you want to run simultaneously

Also try to limit the number of concurrent executions with the `-C, --concurrency NUM` option.

http://knife-zero.github.io/30_subcommands/#converge

**Comment by sawanoboly** [comment]
If the error message is correct, there may be too many files in the recipe. If your environment is macos, try the following command to check the maxfiles.

````
$ ulimit -n
2560
````

If this value is a low number, such as 256, which is the default, try temporarily increasing the limit with the following command and try again.

```
$ ulimit -n NUMBER
```

**Comment by hendych** [comment]
Hi @sawanoboly thanks for the suggestion.
I ran `knife zero converge "name:mynode*" -C 5 -x my_user -P my_password` it throws error

```
ERROR: NoMethodErrorundefined method `send_as_needed' for nil:NilClass
ERROR: /Users/xxx/.gem/gems/knife-zero-2.4.1/lib/knife-zero/net_ssh_multi_patch.rb:94:in `keepalive_if_needed'
     /Users/xxx/.gem/gems/knife-zero-2.4.1/lib/knife-zero/net_ssh_multi_patch.rb:117:in `block in process'
     /Users/xxx/.gem/gems/net-ssh-multi-1.2.1/lib/net/ssh/multi/server_list.rb
```

however after I ran `ulimit -n NUMBER` knife able to run on all my nodes.

### Environment
- Knife 2.4.1
- Chef 17.7.29
