### ISSUE TITLE
When using knife zero, I get "Error Syncing Cookbooks:" every time

### ISSUE THREAD

**Issue by daften** [higanworks/knife-zero#53]
Issue #52 is fixed, so now the role i use in my run_list is resolved, but now I get "Error Syncing Cookbooks:" every time without anything extra in the error message itself. After that follows this output:
```
Running handlers:
localhost [2015-08-19T11:28:55+00:00] ERROR: Running exception handlers
localhost   Running handlers complete
localhost [2015-08-19T11:28:55+00:00] ERROR: Exception handlers complete
localhost [2015-08-19T11:28:55+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
localhost   Chef Client failed. 0 resources updated in 32.987984955 seconds
localhost [2015-08-19T11:28:55+00:00] ERROR: 404 "Not Found "
localhost [2015-08-19T11:28:55+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```

It fails at different times during the sync, so no fixed time or cookbook either. What could be the issue?

**Comment by sawanoboly** [comment]
Could you put command line which you typed ? Or, please tell me how to reproduce your issue and your environment.

And please let me see debug outputs (add `-l debug` to command), if it's alright.

**Comment by daften** [comment]
I use the command ```knife zero bootstrap localhost -N vagrant -E production -u vagrant -r 'role[digipolis_web_build]' -P vagrant -p 2222 -VV``` now. The machine is an empty vagrantbox with machine chef/centos-6.6. The -VV option is because -l debug threw an ambiguous option error.

The output that seems relevant now below:

```
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Status and Header Data: ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: HTTP 1.1 404 Not Found
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-type: application/json
localhost [2015-08-20T11:10:43+00:00] DEBUG: server: chef-zero
localhost [2015-08-20T11:10:43+00:00] DEBUG: access-control-allow-origin: *
localhost [2015-08-20T11:10:43+00:00] DEBUG: date: Thu, 20 Aug 2015 11:22:03 GMT
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-length: 160
localhost [2015-08-20T11:10:43+00:00] DEBUG: connection: close
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Status/Header Data ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Response Body ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: {
localhost   "error": [
localhost     "Object not found: http://127.0.0.1:18889/file_store/repo/cookbooks/chef-solo-search/libraries/vendor/chef/solr_query/lucene_nodes.rb"
localhost   ]
localhost }
localhost
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Response Body -----
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: No content-length information collected for the streamed download, cannot identify streamed download.
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] INFO: HTTP Request Returned 404 Not Found :
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Status and Header Data: ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: HTTP 1.1 404 Not Found
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-type: application/json
localhost [2015-08-20T11:10:43+00:00] DEBUG: server: chef-zero
localhost [2015-08-20T11:10:43+00:00] DEBUG: access-control-allow-origin: *
localhost [2015-08-20T11:10:43+00:00] DEBUG: date: Thu, 20 Aug 2015 11:22:03 GMT
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-length: 138
localhost [2015-08-20T11:10:43+00:00] DEBUG: connection: close
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Status/Header Data ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Response Body ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: {
localhost   "error": [
localhost     "Object not found: http://127.0.0.1:18889/file_store/repo/cookbooks/chef-solo-search/libraries/search/parser.rb"
localhost   ]
localhost }
localhost
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Response Body -----
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: No content-length information collected for the streamed download, cannot identify streamed download.
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] INFO: HTTP Request Returned 404 Not Found :
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Status and Header Data: ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: HTTP 1.1 404 Not Found
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-type: application/json
localhost [2015-08-20T11:10:43+00:00] DEBUG: server: chef-zero
localhost [2015-08-20T11:10:43+00:00] DEBUG: access-control-allow-origin: *
DEBUG: received packet nr 625 type 97 len 12
INFO: channel_close: 6
DEBUG: closing remote forwarded channel
DEBUG: received packet nr 626 type 97 len 12
INFO: channel_close: 7
DEBUG: closing remote forwarded channel
DEBUG: received packet nr 627 type 97 len 12
INFO: channel_close: 8
DEBUG: closing remote forwarded channel
DEBUG: received packet nr 628 type 97 len 12
INFO: channel_close: 9
DEBUG: closing remote forwarded channel
DEBUG: received packet nr 629 type 94 len 4124
INFO: channel_data: 0 4095b
localhost [2015-08-20T11:10:43+00:00] DEBUG: date: Thu, 20 Aug 2015 11:22:03 GMT
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-length: 163
localhost [2015-08-20T11:10:43+00:00] DEBUG: connection: close
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Status/Header Data ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Response Body ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: {
localhost   "error": [
localhost     "Object not found: http://127.0.0.1:18889/file_store/repo/cookbooks/chef-solo-search/libraries/vendor/chef/solr_query/query_transform.rb"
localhost   ]
localhost }
localhost
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Response Body -----
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: No content-length information collected for the streamed download, cannot identify streamed download.
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] INFO: HTTP Request Returned 404 Not Found :
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Status and Header Data: ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: HTTP 1.1 404 Not Found
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-type: application/json
localhost [2015-08-20T11:10:43+00:00] DEBUG: server: chef-zero
localhost [2015-08-20T11:10:43+00:00] DEBUG: access-control-allow-origin: *
localhost [2015-08-20T11:10:43+00:00] DEBUG: date: Thu, 20 Aug 2015 11:22:03 GMT
localhost [2015-08-20T11:10:43+00:00] DEBUG: content-length: 141
localhost [2015-08-20T11:10:43+00:00] DEBUG: connection: close
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Status/Header Data ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- HTTP Response Body ----
localhost [2015-08-20T11:10:43+00:00] DEBUG: {
localhost   "error": [
localhost     "Object not found: http://127.0.0.1:18889/file_store/repo/cookbooks/chef-solo-search/libraries/search/overrides.rb"
localhost   ]
localhost }
localhost
localhost [2015-08-20T11:10:43+00:00] DEBUG: ---- End HTTP Response Body -----
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: No content-length information collected for the streamed download, cannot identify streamed download.
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONToModelOutput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_stream_complete
localhost [2015-08-20T11:10:43+00:00] INFO: HTTP Request Returned 404 Not Found :
localhost
localhost   ================================================================================
localhost   Error Syncing Cookbooks:
localhost   ================================================================================
localhost
localhost [2015-08-20T11:10:43+00:00] DEBUG: Re-raising exception: Net::HTTPServerException - 404 "Not Found "
localhost /opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
localhost   /opt/chef/embedded/apps/chef/lib/chef/http.rb:179:in `streaming_request'
localhost   /opt/chef/embedded/apps/chef/lib/chef/rest.rb:179:in `streaming_request'
localhost   /opt/chef/embedded/apps/chef/lib/chef/rest.rb:117:in `get'
localhost   /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:277:in `download_file'
DEBUG: received packet nr 630 type 94 len 2076
INFO: channel_data: 0 2052b
localhost   /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:254:in `sync_file'
localhost   /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:152:in `block (2 levels) in sync_cookbooks'
localhost   /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:52:in `call'
localhost   /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:52:in `block (3 levels) in process'
localhost   /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:50:in `loop'
localhost   /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:50:in `block (2 levels) in process'
localhost
localhost   Running handlers:
localhost [2015-08-20T11:10:43+00:00] ERROR: Running exception handlers
localhost   Running handlers complete
localhost [2015-08-20T11:10:43+00:00] ERROR: Exception handlers complete
localhost [2015-08-20T11:10:43+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
localhost [2015-08-20T11:10:43+00:00] DEBUG: Net::HTTPServerException: 404 "Not Found "
localhost /opt/chef/embedded/lib/ruby/2.1.0/net/http/response.rb:119:in `error!'
localhost /opt/chef/embedded/apps/chef/lib/chef/http.rb:179:in `streaming_request'
localhost /opt/chef/embedded/apps/chef/lib/chef/rest.rb:179:in `streaming_request'
localhost /opt/chef/embedded/apps/chef/lib/chef/rest.rb:117:in `get'
localhost /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:277:in `download_file'
localhost /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:254:in `sync_file'
localhost /opt/chef/embedded/apps/chef/lib/chef/cookbook/synchronizer.rb:152:in `block (2 levels) in sync_cookbooks'
localhost /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:52:in `call'
localhost /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:52:in `block (3 levels) in process'
localhost /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:50:in `loop'
localhost /opt/chef/embedded/apps/chef/lib/chef/util/threaded_job_queue.rb:50:in `block (2 levels) in process'
localhost   Chef Client failed. 0 resources updated in 28.867708052 seconds
localhost [2015-08-20T11:10:43+00:00] DEBUG: Server doesn't support resource history, skipping resource report.
localhost [2015-08-20T11:10:43+00:00] DEBUG: Audit Reports are disabled. Skipping sending reports.
DEBUG: read 100 bytes
DEBUG: received packet nr 631 type 94 len 76
INFO: channel_data: 0 53b
localhost [2015-08-20T11:10:43+00:00] ERROR: 404 "Not Found "
DEBUG: read 180 bytes
DEBUG: received packet nr 632 type 94 len 156
INFO: channel_data: 0 127b
localhost [2015-08-20T11:10:43+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
DEBUG: read 36 bytes
DEBUG: received packet nr 633 type 96 len 12
INFO: channel_eof: 0
DEBUG: read 104 bytes
DEBUG: received packet nr 634 type 98 len 44
INFO: channel_request: 0 exit-status false
DEBUG: received packet nr 635 type 97 len 12
INFO: channel_close: 0
DEBUG: queueing packet nr 121 type 97 len 28
INFO: closing remaining channels (0 open)
```

It seems there is an error in the chef-solo-search cookbook. I'm trying to switch to chef-zero so I can stop using chef-solo-search :)

**Comment by sawanoboly** [comment]
hmm, It seems using wrong `cookbook_path`...?

Does your cookbook is listed by below command?

`knife cookbook list -z`

**Comment by sawanoboly** [comment]
And, please try https://github.com/higanworks/knife-zero#need-test-on-vagrant- instead of `localhost` for vagrant vm.

**Comment by daften** [comment]
My cookbook path is correct, that was fixed in a previous issue.
knife cookbook list -z contains chef-solo-search (full output below).

And I need to test it this way, because I am not testing my cookbook, but knife zero itself, like I would use it with our actual server ;)

Output for the command:

7-zip                 1.0.2
apache2               3.1.0
apt                   2.8.1
ark                   0.9.0
build-essential       2.2.3
chef-solo-search      0.5.2
chef-sugar            3.1.1
chef_handler          1.2.0
chruby                0.2.2
composer              2.1.0
database              4.0.8
dmg                   2.2.2
git                   4.3.3
homebrew              1.13.0
iis                   4.1.1
iptables              1.0.0
jenkins               2.3.1
jenkins_digipolis     0.1.12
mariadb               0.3.1
mysql                 6.1.0
mysql2_chef_gem       1.0.2
nodejs                2.4.0
openssl               4.3.2
packagecloud          0.0.19
partial_search        1.0.8
pdepend               1.1.0
phing                 0.0.3
php                   1.7.1
php-fpm               0.7.4
phpcpd                1.0.0
phpcs                 1.0.1
phploc                2.0.0
phpmd                 0.0.5
postfix               3.7.0
postgresql            3.4.16
rbac                  1.0.3
ruby_build            0.8.0
runit                 1.7.2
smf                   2.2.7
ssh_known_hosts       2.0.0
sudo                  2.7.2
tar                   0.7.0
windows               1.38.1
xml                   1.2.13
yum                   3.6.3
yum-epel              0.6.2
yum-mysql-community   0.1.17
zip                   1.1.0

**Comment by daften** [comment]
It is very strange, because the files are actually there, it just seems it doesn't find the search directory either. it goes to chef-solo-search/libraries, that's it, further below dirs aren't found.

**Comment by sawanoboly** [comment]
Could you try `private_network` pattern ? 
Using localhost to remote server name will confuse us.

**Comment by daften** [comment]
Using localhost or anything regarding vagrant doesn't seem part of the problem!
The problem seems to lie deeper than knife-zero. It's basically chef-zero that doesn't serve some files. The problem also seems to occur with knife serve e.g. where http://localhost:8889/file_store/repo/cookbooks/chef-solo-search/libraries/vendor isn't found either.

**Comment by sawanoboly** [comment]
Did you use chef-solo-search cookbook with local_mode ?
There is a possibility that the chef-zero doesn't support libraries in nested directory.

**Comment by sawanoboly** [comment]
I got it. It's chef-zero's issue. It doesn't support nested library files with file_store.
Please report to  https://github.com/chef/chef-zero .

Reproduce: under `knife serve`...

```
$ curl http://127.0.0.1:8889/file_store/repo/cookbooks/chef-solo-search/libraries/search.rb
#=> found

$ curl http://127.0.0.1:8889/file_store/repo/cookbooks/chef-solo-search/libraries/search/parser.rb
#=> not found
```

**Comment by daften** [comment]
Thanks, relevant issue opened and cross-referenced.
