### ISSUE TITLE
Gem conflict on newest Chef DK - Unable to activate knife-zero-1.13.2, because chef-12.5.1 conflicts with chef (~> 12.6) (Gem::ConflictError)

### ISSUE THREAD

**Issue by Joseph-R** [higanworks/knife-zero#87]
I am seeing an error running knife-zero to bootstrap an EC2 instance that I do not fully understand.

**Full stack trace:**
```
$ knife zero bootstrap --sudo 10.0.1.205 -E qa --run-list 'recipe[O2O-genie::default]'
/opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:2112:in `raise_if_conflicts': Unable to activate knife-zero-1.13.2, because chef-12.5.1 conflicts with chef (~> 12.6) (Gem::ConflictError)
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/specification.rb:1280:in `activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:198:in `rescue in try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems.rb:195:in `try_activate'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /opt/chefdk/embedded/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/jreid/.chefdk/gem/ruby/2.1.0/gems/knife-zero-1.13.2/lib/chef/knife/zero_apply.rb:2:in `<top (required)>'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `block in load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `each'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:94:in `load_commands'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:104:in `load_command'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife/core/subcommand_loader.rb:118:in `command_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:137:in `subcommand_class_from'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/knife.rb:198:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/lib/chef/application/knife.rb:142:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/chef-12.5.1/bin/knife:25:in `<top (required)>'
	from /usr/local/bin/knife:54:in `load'
	from /usr/local/bin/knife:54:in `<main>'
```

If I'm reading this correctly, it looks like the newest version of knife-zero depends on chef > 12.6.  Okay.  Easy enough.  So I ran a `chef gem update` to pull in the newest version of the chef gem.

**Versions:**
```
$ chef -v
Chef Development Kit Version: 0.10.0
chef-client version: 12.5.1
berks version: 4.0.1
kitchen version: 1.4.2

$ chef gem list | grep -E "(chef|knife)"
chef (12.7.2, 12.5.1)
chef-config (12.7.2, 12.5.1)
chef-dk (0.10.0)
chef-provisioning (1.6.0, 1.5.1, 1.5.0)
chef-provisioning-aws (1.8.0, 1.7.0, 1.6.1)
chef-provisioning-azure (0.5.0, 0.4.0)
chef-provisioning-fog (0.16.0, 0.15.3, 0.15.0)
chef-provisioning-vagrant (0.11.0, 0.10.0)
chef-vault (2.8.0, 2.6.1)
chef-zero (4.5.0, 4.3.2, 1.5.6)
cheffish (2.0.1, 1.6.0)
chefspec (4.5.0, 4.4.0)
knife-spork (1.6.1, 1.5.0)
knife-windows (1.2.1, 1.1.1)
knife-zero (1.13.2, 1.10.2)

# After `chef gem update`
$ chef gem list | grep chef
chef (12.7.2, 12.5.1)
chef-config (12.7.2, 12.5.1)
chef-dk (0.11.0, 0.10.0)
chef-provisioning (1.6.0, 1.5.1, 1.5.0)
chef-provisioning-aws (1.8.0, 1.7.0, 1.6.1)
chef-provisioning-azure (0.5.0, 0.4.0)
chef-provisioning-fog (0.16.0, 0.15.3, 0.15.0)
chef-provisioning-vagrant (0.11.0, 0.10.0)
chef-vault (2.8.0, 2.6.1)
chef-zero (4.5.0, 4.3.2, 1.5.6)
cheffish (2.0.1, 1.6.0)
chefspec (4.5.0, 4.4.0)
```

But I get the same error once chef `12.7.2` is installed.

**Comment by sawanoboly** [comment]
duplicated. please see #84 .

Chef-dk 0.11.0 will be available in few days, maybe.

**Comment by Joseph-R** [comment]
Gotcha.  It's out now, actually.  

For posterity, I was able to resolve by uninstalling the old chef dk and pulling down chef dk `0.11.0`.

**Comment by sawanoboly** [comment]
Oh, thanks for letting me know :+1:
